### ISSUE TITLE
Lite Office in English and with Outlook

### ISSUE THREAD

**Issue by Suleman-Elahi** [WhatTheBlock/Office-Lite#1]
Can you add ISO with Outlook and in English.. it looks in chinese.

Thank you.

**Comment by WhatTheBlock** [comment]
I have uploaded this file: [`config_en_outlook.xml`](https://github.com/WhatTheBlock/Office-Lite/raw/main/config_en_outlook.xml)

First, download the XML file, then download and install Office according to the method provided below.

Download Office
```cmd
setup.exe /download config_en_outlook.xml
```

Install
```cmd
setup.exe /configure config_en_outlook.xml
```
