### ISSUE TITLE
Office 2024 in English Please

### ISSUE THREAD

**Issue by ilovefreesw** [WhatTheBlock/Office-Lite#3]
The 2024 version is not in English.

I tried changing INI file...replaced zh-TW to en-US but then got this error:

![image](https://github.com/WhatTheBlock/Office-Lite/assets/77317006/5d62e02c-48f3-4403-ab44-8bf1b99f1528)

**Comment by WhatTheBlock** [comment]
Update completed.

[Office_LTSC_2024_en_16.0.17628.20116](https://github.com/WhatTheBlock/Office-Lite/releases/tag/ltsc_16.0.17628.20116)
